recipe_sha: a0519562762372ee1c700a87de0ee8dc6457d7b4e13f01c02ddde6346f59ce93  # The commit at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 6.9s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 7.0s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 7.1s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 7.2s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 7.3s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 7.4s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 7.5s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 7.6s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 7.7s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 7.8s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 7.9s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 8.0s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 8.1s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 8.2s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 8.3s
  conda-forge/linux-64 100%[2K[1A[2K[0G[] 8.4s
  [2K[1A[2K[0G[] 8.5s
  [2K[1A[2K[0Gconda-forge/linux-64
  [?25h[34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
  [?25l[2K[0G[] 0.0s
  [2K[1A[2K[0Gopt/conda/conda-bld/linux-64                        ??.?MB @  ??.?MB/s 0 failed  0.0s
  opt/conda/conda-bld/noarch                         127.0 B @ 751.5kB/s  0.0s
  [?25h[34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
  [?25l[2K[0G[] 0.0s
  [2K[1A[2K[0Gopt/conda/conda-bld/linux-64                        ??.?MB @  ??.?MB/s 0 failed  0.0s
  opt/conda/conda-bld/noarch                         127.0 B @   2.6MB/s  0.0s
  [?25hMamba failed to solve:
   - r-base 4.3.*
   - bioconductor-annotationdbi >=1.62.0,<1.63.0
   - bioconductor-annotate >=1.78.0,<1.79.0
   - r-survival
   - bioconductor-biobase >=2.60.0,<2.61.0

  with channels:
   - conda-forge
   - bioconda
   - defaults

  The reported errors are:
  - Encountered problems while solving:
  -   - package bioconductor-annotate-1.78.0-r43hdfd78af_0 is excluded by strict repo priority
  -
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
      solution = solver.solve_for_action(_specs, prefix)
    File "/opt/conda/lib/python3.8/site-packages/boa/core/solver.py", line 244, in solve_for_action
      t = self.solve(specs)
    File "/opt/conda/lib/python3.8/site-packages/boa/core/solver.py", line 234, in solve
      raise RuntimeError("Solver could not find solution."  error_string)
  RuntimeError: Solver could not find solution.Mamba failed to solve:
   - r-base 4.3.*
   - bioconductor-annotationdbi >=1.62.0,<1.63.0
   - bioconductor-annotate >=1.78.0,<1.79.0
   - r-survival
   - bioconductor-biobase >=2.60.0,<2.61.0

  with channels:
   - conda-forge
   - bioconda
   - defaults

  The reported errors are:
  - Encountered problems while solving:
  -   - package bioconductor-annotate-1.78.0-r43hdfd78af_0 is excluded by strict repo priority
  -

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
      call_conda_build(action, config)
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
      result = api.build(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
      return build_tree(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
      packages_from_this = build(metadata, stats,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2038, in build
      output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 787, in expand_outputs
      for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
    File "/opt/conda/lib/python3.8/site-packages/conda_build/metadata.py", line 2524, in get_output_metadata_set
      conda_packages = finalize_outputs_pass(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/metadata.py", line 884, in finalize_outputs_pass
      fm = finalize_metadata(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 547, in finalize_metadata
      build_unsat, host_unsat = add_upstream_pins(m,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 409, in add_upstream_pins
      host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 374, in _read_upstream_pin_files
      deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 131, in get_env_dependencies
      actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 147, in mamba_get_install_actions
      err = DependencyNeedsBuildingError(packages=[str(x) for x in conflict_packages])
    File "/opt/conda/lib/python3.8/site-packages/conda_build/exceptions.py", line 79, in __init__
      raise RuntimeError("failed to parse packages from exception:"
  RuntimeError: failed to parse packages from exception: None
# Last 100 lines of the build log.
