recipe_sha: 1e58f832dccaefefa473b48bc4a7c331878ce790cc6f4b945e5a8b0b3825d3b6  # The commit at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
      solution = solver.solve_for_action(_specs, prefix)
    File "/opt/conda/lib/python3.8/site-packages/boa/core/solver.py", line 244, in solve_for_action
      t = self.solve(specs)
    File "/opt/conda/lib/python3.8/site-packages/boa/core/solver.py", line 234, in solve
      raise RuntimeError("Solver could not find solution."  error_string)
  RuntimeError: Solver could not find solution.Mamba failed to solve:
   - r-ggplot2
   - r-base 4.3.*
   - bioconductor-org.mm.eg.db >=3.17.0,<3.18.0
   - r-rlang
   - r-robustbase
   - bioconductor-annotationdbi >=1.62.0,<1.63.0
   - bioconductor-summarizedexperiment >=1.30.0,<1.31.0
   - libblas 3.9.* *netlib
   - bioconductor-rsubread >=2.14.0,<2.15.0
   - r-scales
   - bioconductor-multiassayexperiment >=1.26.0,<1.27.0
   - r-flexmix
   - r-glue >=1.3.0
   - r-dplyr
   - bioconductor-dropletutils >=1.20.0,<1.21.0
   - r-purrr
   - bioconductor-basilisk >=1.12.0,<1.13.0
   - bioconductor-singlecellexperiment >=1.22.0,<1.23.0
   - libgcc-ng >=12
   - r-stringr
   - bioconductor-s4vectors >=0.38.0,<0.39.0
   - r-data.table
   - r-testthat
   - bioconductor-biostrings >=2.68.0,<2.69.0
   - r-mclust
   - r-matrix >=1.5.0
   - bioconductor-genomicranges >=1.52.0,<1.53.0
   - bioconductor-genomicalignments >=1.36.0,<1.37.0
   - r-magrittr
   - bioconductor-org.hs.eg.db >=3.17.0,<3.18.0
   - r-rcpp >=0.11.3
   - bioconductor-biomart >=2.56.0,<2.57.0
   - bioconductor-rhtslib >=2.2.0,<2.3.0
   - bioconductor-iranges >=2.34.0,<2.35.0
   - bioconductor-biocgenerics >=0.46.0,<0.47.0
   - bioconductor-rsamtools >=2.16.0,<2.17.0
   - bioconductor-zlibbioc >=1.46.0,<1.47.0
   - liblapack 3.9.* *netlib
   - r-ggally
   - r-hash
   - r-mass
   - r-reshape
   - libstdcxx-ng >=12
   - r-reticulate
   - bioconductor-rtracklayer >=1.60.0,<1.61.0
   - r-tibble
   - r-tidyr

  with channels:
   - conda-forge
   - bioconda
   - defaults

  The reported errors are:
  - Encountered problems while solving:
  -   - package bioconductor-dropletutils-1.20.0-r43hf17093f_0 is excluded by strict repo priority
  -

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
      call_conda_build(action, config)
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
      result = api.build(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
      return build_tree(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
      packages_from_this = build(metadata, stats,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2038, in build
      output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 787, in expand_outputs
      for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
    File "/opt/conda/lib/python3.8/site-packages/conda_build/metadata.py", line 2524, in get_output_metadata_set
      conda_packages = finalize_outputs_pass(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/metadata.py", line 884, in finalize_outputs_pass
      fm = finalize_metadata(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 547, in finalize_metadata
      build_unsat, host_unsat = add_upstream_pins(m,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 409, in add_upstream_pins
      host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 374, in _read_upstream_pin_files
      deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 131, in get_env_dependencies
      actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 147, in mamba_get_install_actions
      err = DependencyNeedsBuildingError(packages=[str(x) for x in conflict_packages])
    File "/opt/conda/lib/python3.8/site-packages/conda_build/exceptions.py", line 79, in __init__
      raise RuntimeError("failed to parse packages from exception:"
  RuntimeError: failed to parse packages from exception: None
# Last 100 lines of the build log.
